language: java
jdk:
  - openjdk11
before_install:
  - chmod +x mvnw

jobs:
  include:
    #develop configurations
    - stage: develop
      script: mvn install -Pdevelop
      branches:
        only:
          - develop
    #production configurations
    - stage: production
      script: mvn install -Prelease
      branches:
        only:
          - master