language: java
jdk:
  - openjdk11
before_install:
  - chmod +x mvnw

jobs:
  include:
    #develop configurations
    - stage: develop
      script: mvn install -Pdevelop
      if: branch = develop
      deploy:
        provider: heroku
        api_key:
          secure: $API_KEY_HEROKU
        app: catalogo-pecas-dev
    #production configurations
    - stage: production
      script: mvn install -Prelease
      if: branch = master