language: java
jdk:
  - openjdk11
before_install:
  - chmod +x mvnw

jobs:
  include:
    #develop configurations
    - stage: develop
      script: mvnw install -Pdevelop
      if: branch = develop
      deploy:
        provider: heroku:git
        api_key: $API_KEY_HEROKU
        edge: true
        app: 
          develop: catalogo-pecas-dev
        on:
          branch: develop
    #production configurations
    - stage: production
      script: mvn install -Prelease
      if: branch = master