language: java
jdk:
  - openjdk11
os:
  - windows

jobs:
  include:
    #develop configurations
    - stage: develop
      script: mvn install -Pdevelop
      if: branch = develop
    #production configurations
    - stage: production
      script: mvn install -Prelease
      if: branch = master