language: java
jdk:
  - openjdk11
before_install:
  - chmod +x mvnw

jobs:
  include:
    #develop configurations
    - stage: develop
      script: mvn install -Pdevelop
      if: branch = develop
      deploy:
        provider: heroku
        api_key: $API_KEY_HEROKU
        app: 
          develop: catalogo-pecas-dev
        run: "mvn compile -Pdevelop"
    #production configurations
    - stage: production
      script: mvn install -Prelease
      if: branch = master