backend-legal-pecas:
  application-url: 'http://localhost:${server.port}'
  oauth:
    web-client:
      secret: 'backend-legal-pecas-web'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/legal-pecas-db
    username: postgres
    password: admin

  mail:
    default-encoding: UTF-8
    host: 127.0.0.1 #smtp.gmail.com
    port: 25 #587
    username:
    password:
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
      mail.debug: false

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

server:
  port: 8080