backend-legal-pecas:
  application-url: '${HOST}:${PORT}'
  oauth:
    web-client:
      name: ${WEB_CLIENT_NAME}
      secret: ${WEB_CLIENT_SECRET}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  mail:
    default-encoding: UTF-8
    host: ${HOST_MAIL} #smtp.gmail.com
    port: ${PORT_MAIL} #587
    username: ${USERNAME_MAIL}
    password: ${PASSWORD_MAIL}
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT}