backend-legal-pecas:
  application-url: 'http://localhost:${server.port}'
  oauth:
    web-client:
      secret: ${WEB_CLIENT_SECRET}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

#  mail:
#    default-encoding: UTF-8
#    host: 127.0.0.1 #smtp.gmail.com
#    port: 25 #587
#    username:
#    password:
#    properties:
#      mail.transport.protocol: smtp
#      mail.smtp.auth: false
#      mail.smtp.starttls.enable: false
#      mail.debug: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

server:
  port: ${PORT}